# los datos aparecen en el orden en que agregamos los datos


```mysql
SELECT *
FROM posts
;

```

# ordenar por fecha de publicacion de forma ascendente


```mysql
SELECT *
FROM posts
ORDER BY fecha_publicacion
;



SELECT *
FROM posts
ORDER BY fecha_publicacion ASC
;

```

# # ordenar por fecha de publicacion de forma DESCENDENTE


```
SELECT *
FROM posts
ORDER BY fecha_publicacion DESC
;

```

# Ordenar por cadena , lo ordena por orden alfabetico 


```mysql
SELECT *
FROM posts
ORDER BY titulo ASC
;

```


```mysql
SELECT *
FROM posts
ORDER BY titulo DESC
;

```

# order usuario id


```mysql

SELECT *
FROM posts
ORDER BY usuario_id ASC
;
```

# vamos a limitar a los 5 primeros


```mysql
SELECT *
FROM posts
ORDER BY fecha_publicacion ASC

LIMIT 5
;

```

# HAVING
##  cuantos posts hay  de cualquier year que este activo


```mysql
SELECT MONTHNAME(fecha_publicacion) AS post_month,estatus,COUNT(*) AS post_quantity

FROM posts 
GROUP BY estatus,post_month

ORDER BY post_month

;

```

# 


```mysql
SELECT MONTHNAME(fecha_publicacion) AS post_month,estatus,COUNT(*) AS post_quantity

FROM posts 


GROUP BY estatus,post_month

HAVING post_quantity >1

ORDER BY post_month


;

```