In [1]:
import pandas as pd

import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
url='https://docs.google.com/spreadsheets/d/e/2PACX-1vQMVr8Cy2DN4e5XiTfdlulCQ0daWzEP6YNmccvzgUuWre5IgJ0hmLxi-LfMpqS7T-1msiWIIDR5fehX/pub?output=csv'
df=pd.read_csv(url)
df

,nombreSal,Cloruro De Sodio,Calcio,Fósforo,Magnesio,Azufre,Zinc,Cobre,Yodo,Cobalto,Flúor,Humedad,Selenio,Cromo
0,Supragan,29.0,16,7,0.5,6,0.66,0.15,0.01,0.007,0.07,5,0.0072,NaN
1,Ganazufre 3-14,37.9,12,3,0.3,14,0.56,0.25,0.01,0.005,0.03,5,0.0050,0.0005

In [3]:
df.T

                       0               1
nombreSal          supra  Ganazufre 3-14
Cloruro De Sodio    29.0            37.9
Calcio                16              12
Fósforo                7               3
Magnesio             0.5             0.3
Azufre                 6              14
Zinc                0.66            0.56
Cobre               0.15            0.25
Yodo                0.01            0.01
Cobalto            0.007           0.005
Flúor               0.07            0.03
Humedad                5               5
Selenio           0.0072           0.005
Cromo                NaN          0.0005

In [10]:
df_latex=df.T
print(df_latex.to_latex(index=True,escape=False))

\begin{tabular}{lll}
\toprule
{} &         0 &               1 \\
\midrule
nombreSal        &  Supragan &  Ganazufre 3-14 \\
Cloruro De Sodio &      29.0 &            37.9 \\
Calcio           &        16 &              12 \\
Fósforo          &         7 &               3 \\
Magnesio         &       0.5 &             0.3 \\
Azufre           &         6 &              14 \\
Zinc             &      0.66 &            0.56 \\
Cobre            &      0.15 &            0.25 \\
Yodo             &      0.01 &            0.01 \\
Cobalto          &     0.007 &           0.005 \\
Flúor            &      0.07 &            0.03 \\
Humedad          &         5 &               5 \\
Selenio          &    0.0072 &           0.005 \\
Cromo            &       NaN &          0.0005 \\
\bottomrule
\end{tabular}

<ipython-input-10-4b9fce7f720b>:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(df_latex.to_latex(index=True,escape=False))

In [ ]:
import re
df_df= df_latex.to_latex(index=False)
print(re.sub("textbackslash ", "", df_df))

\begin{tabular}{lll}
\toprule
        Formula &                       Nombre &                     Apodos \\
\midrule
        \ch\{Ca\} &                      CALCIUM &                        NaN \\
     \ch\{CaCO3\} &            CALCIUM CARBONATE &              Piedra caliza \\
      \ch\{CaC2\} &              CALCIUM CARBIDE &                        NaN \\
     \ch\{CaCl2\} &             CALCIUM CHLORIDE &                        NaN \\
     \ch\{CaCN2\} &            CALCIUM CYANAMIDE &                        NaN \\
      \ch\{CaF2\} &             CALCIUM FLUORIDE &                   Fluorita \\
      \ch\{CaH2\} &              CALCIUM HYDRIDE &                        NaN \\
   \ch\{Ca(OH)2\} &            CALCIUM HYDROXIDE & cal hidratada, cal apagada \\
  \ch\{Ca(OCl)2\} &         CALCIUM HYPOCHLORITE &                        NaN \\
  \ch\{Ca(NO3)2\} &              CALCIUM NITRATE &                        NaN \\
       \ch\{CaO\} &                CALCIUM OXIDE &                   cal viva \\
    \ch\{CaHPO4\} &   CALCIUM PHOSPHATE, DIBASIC &                        NaN \\
\ch\{Ca(H2PO4)2\} & CALCIUM PHOSPHATE, MONOBASIC &                        NaN \\
 \ch\{Ca3(PO4)3\} &  CALCIUM PHOSPHATE, TRIBASIC &                        NaN \\
     \ch\{CaSO4\} &              CALCIUM SULFATE &                        NaN \\
\ch\{CaSO4-2H2O\} &                          NaN &                       Yeso \\
       \ch\{CaS\} &              CALCIUM SULFIDE &                        NaN \\
\ch\{CaAl2Si2O8\} &                          NaN &                  Anortita  \\
 \ch\{Ca5FP3O12\} &                          NaN &                   Apatita  \\
\bottomrule
\end{tabular}

<ipython-input-13-96f8d983e152>:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  df_df= df_latex.to_latex(index=False)