In [29]:
import pandas as pd
import numpy as np

#

In [3]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3'],
 'C':['C0','C1','C2','C3'],
 'D':['D0','D1','D2','D3'],
 
 
 })

df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [4]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7'],
 'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7'],
 
 
 })

df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

# concatenar df1 df2

por default se hace por el axis 0 las rows,

## hay algo interesante con los indices

y es que eredan indice anterior 

para corregir esto usamos ingnore_index

In [5]:
pd.concat([df1,df2])

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [6]:
pd.concat([df1,df2],ignore_index=True)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

# ahora por el axis 1 , a nivel de columnas

In [7]:
pd.concat([df1,df2],axis=1)

    A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

# merge

el merge

In [14]:
izq =pd.DataFrame({'key':['k0','k1','k2','k3'],
 'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7']})

der =pd.DataFrame({'key':['k0','k1','k2','k3'],
 'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [15]:
izq

  key   A   B
0  k0  A4  B4
1  k1  A5  B5
2  k2  A6  B6
3  k3  A7  B7

In [16]:
der

  key   C   D
0  k0  C4  D4
1  k1  C5  D5
2  k2  C6  D6
3  k3  C7  D7

# combinacion entre izquierda y derecha
## y pandas lo esta haciendo por las columnas que tienen en comun

In [18]:
izq.merge(der)

  key   A   B   C   D
0  k0  A4  B4  C4  D4
1  k1  A5  B5  C5  D5
2  k2  A6  B6  C6  D6
3  k3  A7  B7  C7  D7

# vamos a hacer el merge sobre una columna especifica, key

In [19]:
izq.merge(der,on='key')

  key   A   B   C   D
0  k0  A4  B4  C4  D4
1  k1  A5  B5  C5  D5
2  k2  A6  B6  C6  D6
3  k3  A7  B7  C7  D7

# voy a cambiar el nombre key  por key_2 y va a fallar cuando solicito que hagar merge poer medio de key

In [20]:
izq =pd.DataFrame({'key':['k0','k1','k2','k3'],
 'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7']})

der =pd.DataFrame({'key_2':['k0','k1','k2','k3'],
 'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [21]:
izq.merge(der,on='key')

KeyError: ignored

# entonces solucionamos idicandole que por un lado tal y el otro tal

In [25]:
izq.merge(der,left_on='key',right_on='key_2')

  key   A   B key_2   C   D
0  k0  A4  B4    k0  C4  D4
1  k1  A5  B5    k1  C5  D5
2  k2  A6  B6    k2  C6  D6
3  k3  A7  B7    k3  C7  D7

# cuando ponemos un valor en nan no concatena

In [30]:
izq =pd.DataFrame({'key':['k0','k1','k2','k3'],
 'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7']})

der =pd.DataFrame({'key_2':['k0','k1','k2',np.nan],
 'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [32]:
der

  key_2   C   D
0    k0  C4  D4
1    k1  C5  D5
2    k2  C6  D6
3   NaN  C7  D7

In [33]:
izq.merge(der,left_on='key',right_on='key_2')

  key   A   B key_2   C   D
0  k0  A4  B4    k0  C4  D4
1  k1  A5  B5    k1  C5  D5
2  k2  A6  B6    k2  C6  D6

# el comando how nos va a salvar la vida y permitir que la del NaN si se una

inner es el valor por default

In [35]:
izq.merge(der,left_on='key',right_on='key_2',how='left')

  key   A   B key_2    C    D
0  k0  A4  B4    k0   C4   D4
1  k1  A5  B5    k1   C5   D5
2  k2  A6  B6    k2   C6   D6
3  k3  A7  B7   NaN  NaN  NaN

In [37]:
izq.merge(der,left_on='key',right_on='key_2',how='inner')

  key   A   B key_2   C   D
0  k0  A4  B4    k0  C4  D4
1  k1  A5  B5    k1  C5  D5
2  k2  A6  B6    k2  C6  D6

In [39]:
izq.merge(der,left_on='key',right_on='key_2',how='right')

   key    A    B key_2   C   D
0   k0   A4   B4    k0  C4  D4
1   k1   A5   B5    k1  C5  D5
2   k2   A6   B6    k2  C6  D6
3  NaN  NaN  NaN   NaN  C7  D7