In [ ]:
tabank de world bank , economia y cosas cool desde hace 50 year

https://data.worldbank.org/

https://data.worldbank.org/indicator/SP.POP.TOTL

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [4]:
%cd '/content/drive/My Drive/Colab Notebooks/pandas/db'
!ls

/content/drive/My Drive/Colab Notebooks/pandas/db
Meteorite_Landings.csv	test.csv  test.json	test.pkl
poblacion.csv		test.hdf  test.parquet	test.xlsx

In [3]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.5'

In [6]:
df_pob=pd.read_csv('poblacion.csv')
df_pob

                       Country  year           pop
0                  Afghanistan  2015  3.441360e+07
1                      Albania  2015  2.880703e+06
2                      Algeria  2015  3.972802e+07
3               American Samoa  2015  5.581200e+04
4                      Andorra  2015  7.801100e+04
...                        ...   ...           ...
1035  Pre-demographic dividend  2018  9.194854e+08
1036              Small states  2018  4.057532e+07
1037                South Asia  2018  1.814389e+09
1038   South Asia (IDA & IBRD)  2018  1.814389e+09
1039        Sub-Saharan Africa  2018  1.078307e+09

[1040 rows x 3 columns]

In [7]:
pd.options.display.float_format='{:,.1f}'.format #para darle el numero de decimales

In [8]:
df_pob

                       Country  year             pop
0                  Afghanistan  2015    34,413,603.0
1                      Albania  2015     2,880,703.0
2                      Algeria  2015    39,728,025.0
3               American Samoa  2015        55,812.0
4                      Andorra  2015        78,011.0
...                        ...   ...             ...
1035  Pre-demographic dividend  2018   919,485,393.0
1036              Small states  2018    40,575,321.0
1037                South Asia  2018 1,814,388,744.0
1038   South Asia (IDA & IBRD)  2018 1,814,388,744.0
1039        Sub-Saharan Africa  2018 1,078,306,520.0

[1040 rows x 3 columns]

vamos a convertir al year en una variable categorica para el uso de multiples indices

In [9]:
df_pob['year']=pd.Categorical(df_pob['year'].apply(str))

In [10]:
df_pob.dtypes

Country      object
year       category
pop         float64
dtype: object

para poner un filtro  ponemos falso para todos los paises y verdadero para los de interes

In [11]:
idx_filtro=df_pob['Country'].isin(['Aruba','Colombia'])
idx_filtro

0       False
1       False
2       False
3       False
4       False
        ...
1035    False
1036    False
1037    False
1038    False
1039    False
Name: Country, Length: 1040, dtype: bool

In [12]:
df_sample=df_pob[idx_filtro]
df_sample

      Country  year          pop
9       Aruba  2015    104,341.0
42   Colombia  2015 47,520,667.0
269     Aruba  2016    104,872.0
302  Colombia  2016 48,171,392.0
529     Aruba  2017    105,366.0
562  Colombia  2017 48,901,066.0
789     Aruba  2018    105,845.0
822  Colombia  2018 49,648,685.0

ahora vamos a crear multiples indices

In [13]:
df_sample.set_index(['Country','year'])

                       pop
Country  year
Aruba    2015    104,341.0
Colombia 2015 47,520,667.0
Aruba    2016    104,872.0
Colombia 2016 48,171,392.0
Aruba    2017    105,366.0
Colombia 2017 48,901,066.0
Aruba    2018    105,845.0
Colombia 2018 49,648,685.0

el sort_index() es para una mejor visualizacion

In [16]:
df_index_sample=df_sample.set_index(['Country','year']).sort_index()
df_index_sample

                       pop
Country  year
Aruba    2015    104,341.0
         2016    104,872.0
         2017    105,366.0
         2018    105,845.0
Colombia 2015 47,520,667.0
         2016 48,171,392.0
         2017 48,901,066.0
         2018 49,648,685.0

si quiero seleccionar colombia

In [19]:
df_index_sample.loc['Colombia',:]

              pop
year
2015 47,520,667.0
2016 48,171,392.0
2017 48,901,066.0
2018 49,648,685.0

In [20]:
df_index_sample.loc['Colombia',:].loc['2016',:]

pop   48,171,392.0
Name: 2016, dtype: float64

In [21]:
df_index_sample.xs(['Aruba'])

           pop
year
2015 104,341.0
2016 104,872.0
2017 105,366.0
2018 105,845.0

In [22]:
df_index_sample.xs(['Aruba','2018'])

pop   105,845.0
Name: (Aruba, 2018), dtype: float64

In [24]:
df_index_sample.xs('2018',level='year')

                  pop
Country
Aruba       105,845.0
Colombia 49,648,685.0

ahora vamos a aplicar lo que aprendimos a todo nuestro conjunto de datos

In [27]:
df_countries=df_pob.set_index(['Country','year']).sort_index()
df_countries

                          pop
Country     year
Afghanistan 2015 34,413,603.0
            2016 35,383,128.0
            2017 36,296,400.0
            2018 37,172,386.0
Albania     2015  2,880,703.0
...                       ...
Zambia      2018 17,351,822.0
Zimbabwe    2015 13,814,629.0
            2016 14,030,390.0
            2017 14,236,745.0
            2018 14,439,018.0

[1040 rows x 1 columns]

In [30]:
df_countries=df_pob.set_index(['Country','year']).sort_index(ascending=[False,True]) #orden alfabetico inverso
df_countries

                          pop
Country     year
Zimbabwe    2015 13,814,629.0
            2016 14,030,390.0
            2017 14,236,745.0
            2018 14,439,018.0
Zambia      2015 15,879,361.0
...                       ...
Albania     2018  2,866,376.0
Afghanistan 2015 34,413,603.0
            2016 35,383,128.0
            2017 36,296,400.0
            2018 37,172,386.0

[1040 rows x 1 columns]

In [31]:
df_countries=df_pob.set_index(['Country','year']).sort_index(ascending=[True,True]) 
df_countries

                          pop
Country     year
Afghanistan 2015 34,413,603.0
            2016 35,383,128.0
            2017 36,296,400.0
            2018 37,172,386.0
Albania     2015  2,880,703.0
...                       ...
Zambia      2018 17,351,822.0
Zimbabwe    2015 13,814,629.0
            2016 14,030,390.0
            2017 14,236,745.0
            2018 14,439,018.0

[1040 rows x 1 columns]

vamos a coger pedsos del dataframe

In [33]:
ids=pd.IndexSlice
df_countries.loc[ids['Aruba':'Austria','2015':'2017'],:].sort_index()

                        pop
Country   year
Aruba     2015    104,341.0
          2016    104,872.0
          2017    105,366.0
Australia 2015 23,815,995.0
          2016 24,190,907.0
          2017 24,601,860.0
Austria   2015  8,642,699.0
          2016  8,736,668.0
          2017  8,797,566.0

In [35]:
 df_countries.index.get_level_values(0)

Index(['Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Albania',
       'Albania', 'Albania', 'Albania', 'Algeria', 'Algeria',
       ...
       'Yemen, Rep.', 'Yemen, Rep.', 'Zambia', 'Zambia', 'Zambia', 'Zambia',
       'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe'],
      dtype='object', name='Country', length=1040)

In [36]:
df_countries.index.get_level_values(1)

CategoricalIndex(['2015', '2016', '2017', '2018', '2015', '2016', '2017',
                  '2018', '2015', '2016',
                  ...
                  '2017', '2018', '2015', '2016', '2017', '2018', '2015',
                  '2016', '2017', '2018'],
                 categories=['2015', '2016', '2017', '2018'], ordered=False, name='year', dtype='category', length=1040)

In [40]:
df_countries['pop']['Colombia']['2018']

49648685.0

In [41]:
df_countries.sum(level='year')

                  pop
year
2015 65,679,147,019.0
2016 66,487,930,677.0
2017 67,294,176,701.0
2018 68,087,886,692.0

convertir alguno de mis indices en columnas

In [47]:
df_index_sample.sort_index()

                       pop
Country  year
Aruba    2015    104,341.0
         2016    104,872.0
         2017    105,366.0
         2018    105,845.0
Colombia 2015 47,520,667.0
         2016 48,171,392.0
         2017 48,901,066.0
         2018 49,648,685.0

In [48]:
df_index_sample.unstack('year')

                  pop
year             2015         2016         2017         2018
Country
Aruba       104,341.0    104,872.0    105,366.0    105,845.0
Colombia 47,520,667.0 48,171,392.0 48,901,066.0 49,648,685.0