In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.5'

In [2]:
df_left = pd.DataFrame(
                      {'X': ['x0', 'x1', 'x2', 'x3'],
                        'W': ['w0', 'w1', 'w2', 'w3'], 
                        'Y': ['y0', 'y1', 'y2', 'y3'] },
                       index=[0,1,2,3])
df_left

    X   W   Y
0  x0  w0  y0
1  x1  w1  y1
2  x2  w2  y2
3  x3  w3  y3

In [3]:
df_right = pd.DataFrame(
                       {'Z': ['z2', 'z3', 'z4', 'z5'],
                         'A': ['a2', 'a3', 'a4', 'a5'], 
                         'Y': ['y2', 'y3', 'y4', 'y5']},
                        index=[2,3,4,5])
df_right

    Z   A   Y
2  z2  a2  y2
3  z3  a3  y3
4  z4  a4  y4
5  z5  a5  y5

In [4]:
pd.merge(df_left,df_right)  #obtenemos un dataframe donde esatan las uniones de las en comun creo

    X   W   Y   Z   A
0  x2  w2  y2  z2  a2
1  x3  w3  y3  z3  a3